### ISSUE TITLE
FormatException when calling IDefaultApi.PendingTransactionInformationAsync

### ISSUE THREAD

**Issue by geoffodonnell** [FrankSzendzielarz/dotnet-algorand-sdk#11]
A call to PendingTransactionInformationAsync results in a System.FormatException when the pending transaction is from an account that has been re-keyed.

**Method Usage**

`await IDefaultApi.PendingTransactionInformationAsync(txId, null);`

**Exception**

**System.FormatException**: 'The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.'

**Comment by geoffodonnell** [comment]
The `ReturnedTransactionConverter` is not properly deserializing the `txn.sgnr` path of the JSON response object. This path maps to the `AuthAddr` property of `SignedTransaction`, which is of type [Address](https://github.com/FrankSzendzielarz/dotnet-algorand-sdk/blob/fb872051ecd3ad5a904186ff9d73fbb1d173211e/dotnet-algorand-sdk/Algod/Model/Address.cs#L16).

Currently, it looks like the call to `Populate` in `ReturnedTransactionConverter` ([here](https://github.com/FrankSzendzielarz/dotnet-algorand-sdk/blob/fb872051ecd3ad5a904186ff9d73fbb1d173211e/dotnet-algorand-sdk/Utils/JsonConverters.cs#L233)) results in NewtonSoft.Json using the Address JsonConstructor, which accepts a `byte[]`, this results in NewtonSoft.Json attempting to convert the serialized value from a `string` to a `byte[]` via `System.Convert.FromBase64String()`.

I would expect [BytesConverter](https://github.com/FrankSzendzielarz/dotnet-algorand-sdk/blob/fb872051ecd3ad5a904186ff9d73fbb1d173211e/dotnet-algorand-sdk/Utils/JsonConverters.cs#L12), which handles this case, to be used when deserializing the Address value. Unsure why it's not, will continue to investigate.

**Stack Trace**

```
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at Newtonsoft.Json.JsonReader.ReadAsBytes()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.Populate(JsonReader reader, Object target)
   at Algorand.Utils.ReturnedTransactionConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in C:\Users\Geoff\Projects\_tmp_\dotnet-algorand-sdk\dotnet-algorand-sdk\Utils\JsonConverters.cs:line 233
```

**Comment by geoffodonnell** [comment]
The JsonConstructor for SignedTransaction is the cause of this issue. Submitted an MR to address it, but changing the constructor signature may have repercussions I've not considered.

**Comment by geoffodonnell** [comment]
On possible workaround here: [ByteArrayConverter.cs](https://github.com/geoffodonnell/dotnet-tinyman-sdk/blob/b4c93041d558c2c25edb3ba1d7cd212baf3dc932/test/Tinyman.IntegrationTestConsole/ByteArrayConverter.cs). Just call `ByteArrayConverter.Attach(...)` on your instance.

**Comment by FrankSzendzielarz** [comment]
Only just saw this! Sorry for the delay! Ok many thanks for the heads up, will address as part of upcoming release.
